### ISSUE TITLE
entrance: does not autostart

### ISSUE THREAD

**Issue by RossComputerGuy** [ExpidusOS/buildroot#4]
@wltjr's Entrance does not autostart on boot even though the preset file is installed, I've cleaned the `output` directory and will check if it does not work still. I suggest others try to see if they experience this problem, I hope to get this fixed before I release the ISO for testing.

**Comment by RossComputerGuy** [comment]
@wltjr, could you look at the package files in `package/entrance/` and see what is going on or tell me what to do to get Entrance to start on boot with systemd?

**Comment by RossComputerGuy** [comment]
The issue does occur on the release, in the next update for testing I'd like to fix this.

**Comment by wltjr** [comment]
I have not tried to run entrance under systemd, and I am unsure if anyone else has tried. Offhand, I think the ```--nodaemon``` option might be causing an issue. You might try removing that part from the service file and see if that makes a difference. If not, then we need to look at any log files or output generated during attempted start, like the entrance.log file at minimum. Assuming, one is generated.

**Comment by RossComputerGuy** [comment]
Alright

**Comment by RossComputerGuy** [comment]
Systemd reports the service is enabled but is inactive, running the enable command and rebooting does enable it though.

**Comment by wltjr** [comment]
Does the problem still exist, or is entrance starting via systemd on boot now?

**Comment by RossComputerGuy** [comment]
Problem persists

**Comment by wltjr** [comment]
Anything in log files? I would remove /var/log/entrance.log and reboot. Then check out that log file after you reboot. Hopefully, there will be some clue on that log file. If not, then maybe a systemd log file.

**Comment by RossComputerGuy** [comment]
Log file does not exist on ISO. When trying a clean build, the log file also does not exist on the HDD disk image.

**Comment by RossComputerGuy** [comment]
Ok, so even enabling Entrance does not fix the issue inside of the OS using a build .img file. It's enabled, vendor enabled, but it says `Active: inactive (dead)`. I can start Entrance using systemd and run it from the terminal.

**Comment by RossComputerGuy** [comment]
Ok, I found the issue. The default target needs to be set to `graphical.target`. I just need to figure out how to set it to that by default.

**Comment by wltjr** [comment]
Ok, so it had to do with how it was started under systemd, or how the service was classified. I need to get some experience working with systemd. I have mostly avoided it thus far.

**Comment by RossComputerGuy** [comment]
Yeah, so look at how other display managers' run with systemd.
